"""empty message

Revision ID: eda166fd66a9
Revises: e8b87886996f
Create Date: 2023-05-05 23:28:01.694672

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eda166fd66a9"
down_revision = "e8b87886996f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=15), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=40), nullable=False),
        sa.Column("email", sa.VARCHAR(length=90), nullable=False),
        sa.Column("picture_url", sa.TEXT(), nullable=False),
        sa.Column("hashed_password", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("profiles")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=15), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=40), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=90), autoincrement=False, nullable=False),
        sa.Column("picture_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="profiles_pkey"),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
