"""empty message

Revision ID: 88e527bdc3f3
Revises: 0a61f21f7831
Create Date: 2023-05-18 22:00:48.536076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88e527bdc3f3"
down_revision = "0a61f21f7831"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template_type",
        sa.Column("title", sa.VARCHAR(length=50), nullable=False),
        sa.Column("picture_url", sa.VARCHAR(length=2000), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "business_card",
        sa.Column("job_title", sa.VARCHAR(length=50), nullable=False),
        sa.Column("specificity", sa.VARCHAR(length=50), nullable=False),
        sa.Column("phone", sa.VARCHAR(length=16), nullable=True),
        sa.Column("email", sa.VARCHAR(length=254), nullable=False),
        sa.Column("address", sa.TEXT(), nullable=True),
        sa.Column("first_name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("tg_url", sa.VARCHAR(length=50), nullable=True),
        sa.Column("vk_url", sa.VARCHAR(length=50), nullable=True),
        sa.Column("fb_url", sa.VARCHAR(length=50), nullable=True),
        sa.Column("own_site_url", sa.VARCHAR(length=2000), nullable=True),
        sa.Column("cv_url", sa.VARCHAR(length=2000), nullable=True),
        sa.Column("company_logo", sa.TEXT(), nullable=True),
        sa.Column("bio", sa.VARCHAR(length=500), nullable=True),
        sa.Column("bc_template_type", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["bc_template_type"], ["template_type.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "business_card_owner",
        sa.Column("owner", sa.UUID(), nullable=False),
        sa.Column("card", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["card"], ["business_card.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("businesscard")
    op.alter_column("users", "hashed_password", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.TEXT(), nullable=False)
    op.create_table(
        "businesscard",
        sa.Column("job_title", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("specificity", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(length=12), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(length=254), autoincrement=False, nullable=False),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("first_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("tg_url", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("vk_url", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("fb_url", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("own_site_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("summary_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("company_logo", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("bio", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("bc_template_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="businesscard_pkey"),
    )
    op.drop_table("business_card_owner")
    op.drop_table("business_card")
    op.drop_table("template_type")
    # ### end Alembic commands ###
